version: '3.8'

services:
  svg-previewer:
    build: .
    container_name: svg-previewer
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      # 如果需要扫描特定目录，可以挂载
      # - /path/to/svg/files:/app/scanned-files:ro
      - ./logs:/app/logs
    networks:
      - svg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: svg-previewer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - svg-previewer
    restart: unless-stopped
    networks:
      - svg-network

networks:
  svg-network:
    driver: bridge 